### ISSUE TITLE
Finished ContactList Exercise

### ISSUE THREAD

**Issue by pbrandstetter** [htl-perg-2019-20-5bhif/contact-list-exercise-pbrandstetter#1]
Dear Mr. Stropek,
I have finished my homework regarding the contact-list.
Kind regards,
Philipp Brandstetter

**Comment by rstropek** [comment]
Avoid checking in unnecessary files (e.g. *bin*, *.vscode*).

**Comment by rstropek** [comment]
Otherwise well done, the extra point is yours.

Greetings,
Rainer Stropek.
